[package]
name = "rust-crypto"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
sha2 = "0.10"
hmac = "0.12"
bip38 = "1.1.1"
hex = "0.4"
base64 = "0.22.1"