/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_debugtester_free: (a: number, b: number) => void;
export const debugtester_test_basic_creation: () => [number, number, number, number];
export const debugtester_test_hash_functions: () => [number, number, number, number];
export const debugtester_test_wots_params: () => [number, number, number, number];
export const debugtester_test_base_w_conversion: (a: any) => [number, number, number, number];
export const debugtester_test_single_chain: () => [number, number, number, number];
export const debugtester_test_signing_pipeline: () => [number, number, number, number];
export const debugtester_test_memory_access: () => [number, number, number, number];
export const __wbg_wasmxmsskeypair_free: (a: number, b: number) => void;
export const __wbg_wasmxmsssignature_free: (a: number, b: number) => void;
export const __wbg_wasmxmsspublickey_free: (a: number, b: number) => void;
export const wasmxmsskeypair_new: (a: number, b: number) => [number, number, number];
export const wasmxmsskeypair_public_key: (a: number) => number;
export const wasmxmsskeypair_sign: (a: number, b: any) => [number, number, number];
export const wasmxmsskeypair_remaining_signatures: (a: number) => bigint;
export const wasmxmsskeypair_max_signatures: (a: number) => bigint;
export const wasmxmsskeypair_export_private_key: (a: number) => any;
export const wasmxmsskeypair_parameter_info: (a: number) => [number, number];
export const wasmxmsssignature_bytes: (a: number) => any;
export const wasmxmsspublickey_bytes: (a: number) => any;
export const wasmxmsspublickey_size: (a: number) => number;
export const wasmxmsspublickey_from_bytes: (a: any) => number;
export const wasmxmsspublickey_verify: (a: number, b: any, c: number) => [number, number, number];
export const __wbg_wasmutils_free: (a: number, b: number) => void;
export const wasmutils_get_parameter_sets: () => any;
export const wasmutils_version_info: () => [number, number];
export const wasmutils_benchmark_parameter_set: (a: number) => any;
export const init_cryptkeyper: () => [number, number];
export const check_webcrypto_support: () => number;
export const wasmxmsssignature_size: (a: number) => number;
export const main: () => void;
export const wasmutils_generate_random_seed: () => any;
export const wasmxmsssignature_from_bytes: (a: any) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
